### ISSUE TITLE
Investigate panic in engine worker

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/dealbot#230]
See logs: https://app.logz.io/#/goto/3924dfee8a92d8f51a7b2eef2e00cb82?switchToAccountId=104138

```

Jun 16, 2021 @ 16:07:06.966 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1486977] | &nbsp;
-- | -- | --

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | created by github.com/filecoin-project/dealbot/engine.(*Engine).run | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | /go/src/app/engine/engine.go:99 +0xe5 | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | /go/src/app/engine/engine.go:260 +0x657 | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | panic: runtime error: invalid memory address or nil pointer dereference | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | /go/src/app/engine/engine.go:189 +0x270 | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | github.com/filecoin-project/dealbot/engine.(*Engine).worker(0xc0007180c0, 0x5, 0xc000387f80) | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | goroutine 74 [running]: | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | github.com/filecoin-project/dealbot/engine.(*Engine).runTask(0xc0007180c0, 0x1ba9cc0, 0xc000791ec0, 0x0, 0x1, 0x5) | &nbsp;

&nbsp; | &nbsp; | Jun 16, 2021 @ 16:07:06.966 | &nbsp;

<br class="Apple-interchange-newline">
```

**Comment by willscott** [comment]
fixed in #238
